name: Integracion Continua

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build del proyecto
        run: mvn clean compile

      - name: Ejecutar pruebas automatizadas
        run: mvn test surefire-report:report

      - name: Acceptance Test Gate
        run: mvn test

      - name: Deployment simulado
        run: |
          echo "Acceptance Test Gate aprobado"
          echo "Iniciando despliegue de la version validada"
          echo "Deployment completado correctamente"

      - name: Publicar reporte de pruebas
        uses: actions/upload-artifact@v4
        with:
          name: reporte-pruebas-surefire
          path: target/reports/

      - name: Publicar reporte BDD de Cucumber
        uses: actions/upload-artifact@v4
        with:
          name: reporte-bdd-cucumber
          path: target/cucumber-report.html